"""empty message

Revision ID: 0ead70782759
Revises: a710811a2e3a
Create Date: 2018-12-04 15:05:59.730058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ead70782759'
down_revision = 'a710811a2e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'earnings',
               existing_type=mysql.VARCHAR(length=80),
               nullable='0')
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['id'])
    op.add_column('sm_user', sa.Column('is_admin', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sm_user', 'is_admin')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.alter_column('products', 'earnings',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
