"""empty message

Revision ID: 407cb3c7351d
Revises: d632fa975355
Create Date: 2018-12-04 15:44:48.156058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '407cb3c7351d'
down_revision = 'd632fa975355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'earnings',
               existing_type=mysql.VARCHAR(length=80),
               nullable='0')
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['id'])
    op.drop_column('sm_user', 'is_admin111')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sm_user', sa.Column('is_admin111', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.alter_column('products', 'earnings',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
