"""empty message

Revision ID: d632fa975355
Revises: 0ead70782759
Create Date: 2018-12-04 15:42:57.201058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd632fa975355'
down_revision = '0ead70782759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'earnings',
               existing_type=mysql.VARCHAR(length=80),
               nullable='0')
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['id'])
    op.add_column('sm_user', sa.Column('is_admin111', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sm_user', 'is_admin111')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.alter_column('products', 'earnings',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
