"""empty message

Revision ID: e26e661a9b9e
Revises: d4485a83d1cf
Create Date: 2018-11-16 16:50:41.119970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26e661a9b9e'
down_revision = 'd4485a83d1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('enable_msg', sa.String(length=200), nullable=False),
    sa.Column('blank_name', sa.String(length=200), nullable=False),
    sa.Column('minwith', sa.Integer(), nullable=True),
    sa.Column('withwas', sa.Integer(), nullable=True),
    sa.Column('withtax', sa.Float(), nullable=True),
    sa.Column('mintransfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    # ### end Alembic commands ###
